import type { Metadata } from 'next';
// import { Geist, Geist_Mono } from 'next/font/google';
import { Inter } from 'next/font/google';
import './globals.css';

import AppProviders from '@/components/providers/AppProviders';
import AuthHydrator from '@/components/providers/AuthHydrator';
import { Toaster } from '@/components/ui/sonner';

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// });

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// });

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800'],
  variable: '--font-inter', // Mendaftarkannya sebagai variabel CSS
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' suppressHydrationWarning>
      {/* 💡 Explicitly pass the variable class along with its raw styling definition mapping */}
      <body
        className={`${inter.variable} font-sans antialiased`}
        style={{ fontFamily: 'var(--font-inter), sans-serif' }}
      >
        <AppProviders>
          <AuthHydrator>{children}</AuthHydrator>
        </AppProviders>
        <Toaster position='top-right' richColors closeButton />
      </body>
    </html>
  );
}
